#  Este es un archivo de rubocop simple donde se deshabilitan
# muchas de las reglas que suele checkear rubocop, para dejar
# una base simple y se tengan que preocupar solo de ciertos "cops"

#  Al final de este archivo, si encuentras que te ayudaría a tener
# un código mas ordenado, puedes añadir todos los cops que creas convenientes.



AllCops:
  TargetRubyVersion: 2.6 parser
  SuggestExtensions: false
  DisabledByDefault: true
  NewCops: disable
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'app/views/**/*'
    - 'config/environments/*'
    - 'node_modules/**/*'
    - 'generated/**/*.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

    

# Metrics

Metrics/AbcSize:
  Max: 50
  Enabled: true

Metrics/BlockLength:
  Max: 100
  Enabled: true

# Layout
Layout/LineLength:
  Max: 200
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/ArgumentAlignment:
  Enabled: true
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/ArrayAlignment:
  Enabled: true

# Naming
Naming/ConstantName:
  Enabled: true
Naming/FileName:
  Enabled: true
Naming/MethodName:
  Enabled: true
Naming/AsciiIdentifiers:
  Enabled: true
Naming/BlockParameterName:
  Enabled: false
  MinNameLength: 2
Naming/VariableName:
  Enabled: true

# Style 
Style/Documentation:
  Enabled: false
Style/Next:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantParentheses:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/DoubleNegation:
  Enabled: true
Style/EmptyElse:
  Enabled: true

# Lint
Lint/EmptyFile:
  Enabled: false
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperator:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/RedundantWithIndex:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: false
Lint/EmptyBlock:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
Lint/EmptyExpression:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/ShadowedArgument:
  Enabled: true
Lint/Syntax:
  Enabled: true

### Añade aquí todos los Cops que quieras:
